name: quart
channels:
  - conda-forge
  - maxyme
dependencies:
  - python =3.7.1
  - quart =0.6.10
  - quart-cors =0.1.0
  - quart-openapi =1.3.8
  - curio =0.9
  - asyncpg =0.18.2
  - asks =2.2.0
  - pytest =4.0.1
  - pytest-asyncio =0.9.0